<a href="https://colab.research.google.com/github/OkeyNich/OkeyNich/blob/main/Copy_of_Stage_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# convention for importing numpy
import numpy as np

In [ ]:
arr = [6, 7, 8, 9]
print(type(arr)) # prints <class 'list'>

<class 'list'>


In [ ]:
a = np.array(arr)
print(type(a))  # prints <class 'numpy.ndarray'>
print(a.shape)  # prints (4,) - a is an 1d array with 4 items
print(a.dtype)  # prints int64

<class 'numpy.ndarray'>
(4,)
int64


In [ ]:
# get the dimension of a with ndim 
print(a.ndim)   # prints 1

1


In [ ]:
b = np.array([[1, 2, 3] + [4, 5, 6]])
print(b)

[[1 2 3 4 5 6]]


In [ ]:
c = np.array([1,2,3,4])
d = np.array([5,6,7,8])
E = np.array([c] + [d])
print(c+d)
print(E)

[ 6  8 10 12]
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(b.ndim)   # prints 2
b.shape         # prints (2, 3)

2


(1, 6)