<a href="https://colab.research.google.com/github/OkeyNich/OkeyNich/blob/main/Nich0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
arr = [6,7,8,9]
print(type(arr))

<class 'list'>


In [3]:
a=np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print (a)

[6 7 8 9]


In [5]:
print(a.shape)

(4,)


In [6]:
# Get the dimension of a with ndim
print(a.ndim)

1


In [8]:
b= np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [9]:
print(b.ndim)

2


In [10]:
print(b.shape)

(2, 3)


In [21]:
s = b.reshape(3,2)

In [23]:
s

array([[1, 2],
       [3, 4],
       [5, 6]])

To reshape an array you must make sure that the multiplication of whatever numbers you want use must be equal to the last number in the array you want to reshape. Example above shows that 3x2 will give you 6. we can us 3x2x1 or 2x3x1 etc.

In [24]:
# a 2x3 array with random values
np.random.random((2,3))

array([[0.61260934, 0.71572462, 0.63212447],
       [0.20303614, 0.0550135 , 0.26251964]])

In [25]:
# a 2x3 array of zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
# a 2x3 array of ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
# a 3x3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

The codes 24 to 30 are some inbuilt functions that can be used to initialse numpy, which include empty(), zeros(), ones(), full(), random.random().

In [31]:
c = np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])

In [32]:
d = np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])

In [33]:
c+d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [34]:
c*d

array([[36., 40., 42.],
       [ 9., 16., 21.]])

In [36]:
5/d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [37]:
c**2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])

The codes 33 to 37 shows how you can combine or work with 2arrays

In [38]:
#Indexing with Arrays & Using Arrays for Data Processing.
a[0], a[3]

(6, 9)

In [39]:
b[0,0]

1

In [40]:
b[1,2]

6

In [41]:
c[0,1]

8.0

In [42]:
# Elements in array can also be retrieved by slicing rows and columns or combination of indexing and slicing.
d[1,0:2]

array([9., 8.])

In [44]:
e=np.array([[10,11,12],[13,14,15],
            [16,17,18],[19,20,21]])


In [45]:
# Slicing
e[:3,:2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [46]:
# integer indexing
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [47]:
e[e>15]

array([16, 17, 18, 19, 20, 21])