<a href="https://colab.research.google.com/github/OkeyNich/OkeyNich/blob/main/OKey_numpy_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# convention for importing numpy
import numpy as np

arr = [6, 7, 8, 9]
print(type(arr)) # prints <class 'list'>

a = np.array(arr)
print(type(a))  # prints <class 'numpy.ndarray'>
print(a.shape)  # prints (4,) - a is a 1d array with 4 items
print(a.dtype)  # prints int64

# get the dimension of a with ndim 
print(a.ndim)   # prints 1

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)        # prints [[1 2 3 ],[4 5 6]]
print(b.ndim)   # prints 2
b.shape         # prints (2, 3) - b a 2d array with 2 rows and     3 columns
import numpy as np

arr = [6, 7, 8, 9]
print(type(arr)) # prints <class 'list'>

a = np.array(arr)
print(type(a))  # prints <class 'numpy.ndarray'>
print(a.shape)  # prints (4,) - a is a 1d array with 4 items
print(a.dtype)  # prints int64

# get the dimension of a with ndim 
print(a.ndim)   # prints 1

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)        # prints [[1 2 3],[4 5 6]]
print(b.ndim)   # prints 2
b.shape         # prints (2, 3) - b a 2d array with 2 rows and     3 columns


<class 'list'>
<class 'numpy.ndarray'>
(4,)
int64
1
[[1 2 3]
 [4 5 6]]
2
<class 'list'>
<class 'numpy.ndarray'>
(4,)
int64
1
[[1 2 3]
 [4 5 6]]
2


(2, 3)